export const clients = [
    {
        idclient: 1,
        firstName: 'Hervé',
        lastName: 'Padilla',
        companyName: 'IFA Metz',
        date: '2023-01-21',
        address1: '10 Rue de la Liberté',
        address2: 'Bâtiment A',
        postalCode: '57000',
        city: 'Metz',
        country: 'France',
        jobTitle: 'Directeur',
        phone: '0601234567',
        email: 'herve.padilla@ifametz.fr'
    },
    {
        idclient: 2,
        firstName: 'John',
        lastName: 'Favreau',
        companyName: 'LucasFilm',
        date: '2024-01-21',
        address1: '12 Rue des Écoles',
        address2: '',
        postalCode: '75005',
        city: 'Paris',
        country: 'France',
        jobTitle: 'Réalisateur',
        phone: '0612345678',
        email: 'john.favreau@lucasfilm.com'
    },
    {
        idclient: 3,
        firstName: 'Beyonce',
        lastName: '',
        companyName: 'JayZ inc.',
        date: '2024-01-21',
        address1: '5 Avenue des Champs-Élysées',
        address2: '',
        postalCode: '75008',
        city: 'Paris',
        country: 'France',
        jobTitle: 'Chanteuse',
        phone: '0623456789',
        email: 'beyonce@jayzinc.com'
    },
    {
        idclient: 4,
        firstName: 'Luc',
        lastName: 'Skywalker',
        companyName: 'La Force',
        date: '2024-01-21',
        address1: '1 Place de la Concorde',
        address2: '',
        postalCode: '75008',
        city: 'Paris',
        country: 'France',
        jobTitle: 'Jedi',
        phone: '0634567890',
        email: 'luc.skywalker@laforce.fr'
    },
    {
        idclient: 5,
        firstName: 'Carlos',
        lastName: 'Santana',
        companyName: 'Santana Band',
        date: '2024-01-21',
        address1: '20 Rue de la Musique',
        address2: '',
        postalCode: '33000',
        city: 'Bordeaux',
        country: 'France',
        jobTitle: 'Guitariste',
        phone: '0645678901',
        email: 'carlos.santana@santanaband.com'
    },
    {
        idclient: 6,
        firstName: 'M',
        lastName: 'Philippe',
        companyName: 'Oculture',
        date: '2024-01-21',
        address1: 'Buhlhaven 60',
        address2: 'BAT 2',
        postalCode: '2498',
        city: 'Hellerup',
        country: 'Denmark',
        jobTitle: 'Directeur artistique',
        phone: '0656789012',
        email: 'm.philippe@oculture.fr'
    },
    {
        idclient: 7,
        firstName: 'John',
        lastName: 'Smith',
        companyName: 'NORAUTO France',
        date: '2024-01-21',
        address1: '22 Boulevard de la République',
        address2: '',
        postalCode: '59800',
        city: 'Lille',
        country: 'France',
        jobTitle: 'Chef de projet',
        phone: '0667890123',
        email: 'john.smith@norauto.fr'
    },
    {
        idclient: 8,
        firstName: 'Carlita',
        lastName: 'Bonita',
        companyName: 'Bonita inc.',
        date: '2024-01-21',
        address1: 'chaussée Verbeke 98',
        address2: '',
        postalCode: '9186',
        city: 'Malmedy',
        country: 'Belgium',
        jobTitle: 'PDG',
        phone: '0678901234',
        email: 'carlita.bonita@bonitainc.com'
    },
    {
        idclient: 9,
        firstName: 'John',
        lastName: 'Ciseaux',
        companyName: 'Ciseaux coiffure',
        date: '2024-01-21',
        address1: '18 Rue de la Beauté',
        address2: '',
        postalCode: '13001',
        city: 'Marseille',
        country: 'France',
        jobTitle: 'Coiffeur',
        phone: '0689012345',
        email: 'john.ciseaux@ciseauxcoiffure.fr'
    },
    {
        idclient: 10,
        firstName: 'Mar',
        lastName: 'Lapelle',
        companyName: 'Construction Lapelle',
        date: '2024-01-21',
        address1: '25 Rue de la Construction',
        address2: '',
        postalCode: '69007',
        city: 'Lyon',
        country: 'France',
        jobTitle: 'Entrepreneur',
        phone: '0690123456',
        email: 'mar.lapelle@constructionlapelle.fr'
    },
    {
        idclient: 11,
        firstName: 'Fatima',
        lastName: 'Glow',
        companyName: 'Gloss et compagnie',
        date: '2024-01-21',
        address1: '8 Rue de la Beauté',
        address2: '',
        postalCode: '67000',
        city: 'Strasbourg',
        country: 'France',
        jobTitle: 'Maquilleuse',
        phone: '0609876543',
        email: 'fatima.glow@glossetcompagnie.fr'
    },
    {
        idclient: 12,
        firstName: 'Jim',
        lastName: 'Carey',
        companyName: 'Yes entreprise',
        date: '2024-01-21',
        address1: '12 Rue du Sourire',
        address2: '',
        postalCode: '31000',
        city: 'Toulouse',
        country: 'France',
        jobTitle: 'Comédien',
        phone: '0612345679',
        email: 'jim.carey@yesentreprise.com'
    },
    {
        idclient: 13,
        firstName: 'John',
        lastName: 'Doe',
        companyName: 'Inconnu au bataillon',
        date: '2024-01-21',
        address1: '99 Rue de l’Inconnu',
        address2: '',
        postalCode: '75001',
        city: 'Paris',
        country: 'France',
        jobTitle: 'Mystérieux',
        phone: '0623456780',
        email: 'john.doe@inconnu.com'
    }
];
